version: "3.7"

services:
  elasticsearch:
    image: elastic/elasticsearch:7.5.1
    environment:
      - "discovery.type=single-node"
      - "xpack.monitoring.collection.enabled=true"
    networks:
      - elk
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200

  kibana:
    image: elastic/kibana:7.5.1
    ports:
      - "127.0.0.1:5601:5601"
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "xpack.monitoring.collection.enabled=true"
    networks:
      - elk

  metricbeat-index-management:
    image: elastic/metricbeat:7.5.1
    command: setup --index-management
          -E output.logstash.enabled=false
          -E 'output.elasticsearch.hosts=["elasticsearch:9200"]'
          -E setup.template.settings.index.number_of_replicas=0
          -E setup.template.overwrite=true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
    networks:
      - elk

networks:
  elk:

volumes:
  esdata:
