version: '3.7'

services:

  portainer:
    image: portainer/portainer
    command: -H "tcp://tasks.portainer-agent:9001" --tlsskipverify --no-auth
    ports:
      - 0.0.0.0:9000:9000
    networks:
      - portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer
    deploy:
      mode: global

networks:
  portainer:
